services:
  app:
    build: .
    container_name: restaurante-app
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 9000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: restaurante_user
      DB_PASSWORD: restaurante_pass
      DB_NAME: restaurante

  db:
    image: mysql:8.4
    container_name: restaurante-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: restaurante
      MYSQL_USER: restaurante_user
      MYSQL_PASSWORD: restaurante_pass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot_secret"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 20s
